app/post/models.py
from typing import Optional
from app import db
from datetime import datetime, timezone
import sqlalchemy as sa
import sqlalchemy.orm as so


class Posts(db.Model):
    __tablename__ = "posts"

    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    title: so.Mapped[str] = so.mapped_column(sa.String(255))
    author: so.Mapped[str] = so.mapped_column(sa.String(255))
    body: so.Mapped[str] = so.mapped_column(sa.Text)
    slug: so.Mapped[str] = so.mapped_column(sa.String(255), unique=True)
    created: so.Mapped[Optional[datetime]] = so.mapped_column(default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f'<Post id {self.id}, title: {self.title}>'

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea

class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    body = StringField('Содержание', validators=[DataRequired()], widget=TextArea())
    author = StringField('Автор', validators=[DataRequired()])
    submit = SubmitField('Отправить')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    # Create app blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .post import post as post_blueprint
    app.register_blueprint(post_blueprint)
    
    return app

app/main/__init__.py
from app.main.views import main

app/main/views.py
from flask import Blueprint, render_template
from app.post.models import Posts

main = Blueprint('main', __name__)

@main.route('/')
def index():
    posts = Posts.query.order_by(Posts.created)
    return render_template('main/index.html', title="Главная", posts=posts)

app/post/__init__.py
from app.post.views import post

app/post/views.py
from flask import Blueprint, flash, render_template
from app import db
from app.post.forms import PostForm
from app.post.models import Posts
from slugify import slugify

post = Blueprint('post', __name__, url_prefix='/post')

@post.route('/add-post', methods=['GET', 'POST'])
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Posts(title=form.title.data, body=form.body.data, author=form.author.data)
        post.slug = slugify(post.title)
        # Очистка формы
        form.title.data = ''
        form.author.data = ''
        form.body.data = ''
        # Добавление поста в БД
        db.session.add(post)
        db.session.commit()

        flash('Заметка создана успешно')
    return render_template('post/add_post.html', title="Записи", form=form)

@post.route('/<slug>')
def post_detail(slug):
    post = Posts.query.filter(Posts.slug == slug).first()
    return render_template('post/detail_post.html', post=post)

app/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('main.index') }}">Типичный
              блог</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{
                        url_for('main.index') }}">Главная</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{
                        url_for('post.add_post') }}">Создать</a>
              </li>
            </ul>
            <ul>
                <form class="d-flex" role="search">
                    <input class="form-control mr-sm-1" type="search" placeholder="Поиск" aria-label="Search">
                    <button class="btn btn-outline-light" type="submit">Поиск</button>
                </form>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Войти</a>
                </li>
            </ul>
          </div>
        </div>
      </nav>
    <br>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/main/index.html
{% extends 'base.html' %}

{% block content %}

    {% for message in get_flashed_messages() %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

{% for post in posts %}
    <h2><a href="{{ url_for('post.post_detail', slug=post.slug) }}">{{ post.title }}</a></h2>
    <small>
    Автор <button type="button" href="#" class="btn btn-danger btn-sm">{{ post.author }}</button>
    Дата создания <button type="button" href="#" class="btn btn-secondary btn-sm">{{ post.created }}</button>
    </small>
    <br><br><br>
    {{ post.content }}<br><br>
{% endfor %}

{% endblock %}

app/templates/post/add_post.html
{% extends 'base.html' %}

{% block content %}

    {% for message in get_flashed_messages() %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <h1>Создать запись</h1>
    <br>
    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
        <form action="" method="POST">
            {{ form.hidden_tag() }}

            {{ form.title.label(class="form-label") }}<br>
            {{ form.title(class="form-control") }}<br>

            {{ form.author.label(class="form-label") }}<br>
            {{ form.author(class="form-control") }}<br>

            {{ form.body.label(class="form-label") }}<br>
            {{ form.body(class="form-control", rows="10") }}<br>

            <br>
            {{ form.submit(class="btn btn-secondary") }}
        </form>
    </div>

{% endblock %}

app/templates/post/detail_post.html
{% extends 'base.html' %}

{% block content %}

    {% for message in get_flashed_messages() %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <p>{{ post.body }}</p>
    
    
{% endblock %}